#!/bin/bash
#DEBUG=-debug

CERTDIR=$(dirname $(realpath $0))/certs
if [ "$1" == "" ]; then
    CERT=$CERTDIR/malte_key_and_cert_brainpoolP160r1.pem
else
    CERT=$1
fi
CA=$CERTDIR/CAchain.pem

#################################################################################
echo -e "$ openssl version"
openssl version

echo -e "\n$ openssl s_client -connect localhost:636 $DEBUG -CAfile $CA -cert $CERT -verify 2"
openssl s_client -connect localhost:636 $DEBUG -CAfile $CA -cert $CERT -verify 2
status=$?
echo -e "\n STATUS=$status"

exit 0
