#!/bin/bash

if [ "$1" == "" ]; then
    CERT=malte_key_and_cert_brainpoolP160r1.pem
else
    CERT=$1
fi

CERTDIR=$(dirname $(realpath $0))/certs
#DEBUG=-debug
echo -e "$ openssl version"
openssl version

echo -e "\n$ openssl s_client -connect localhost:636 $DEBUG -CAfile $CERTDIR/CAchain.pem -cert $CERTDIR/$CERT -verify 2"
openssl s_client -connect localhost:636 $DEBUG -CAfile $CERTDIR/CAchain.pem -cert $CERTDIR/$CERT -verify 2
