#!/bin/bash
set -e

if [ "$#" = 1 ]; then
    TAG=$1
else
    TAG=v2_02_171
fi
git tag | grep $TAG >/dev/null
if [ $? -ne 0 ]; then
    echo tag: $TAG missing
    exit
fi

BRANCH=$(echo $TAG | sed 's/v/b/')

cd /root/lvm2
make distclean || true
git checkout $BRANCH 2> /dev/null || git checkout -b $BRANCH $TAG;
git lver -5
#./configure --enable-lvmetad --enable-debug --enable-udev_sync --enable-udev_rules
./configure --enable-lvmetad --enable-debug
make
make install

lvm version
