FROM ubuntu:18.10
MAINTAINER Anders Wallin

WORKDIR /root

ENV TERM xterm
ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y apt-utils
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y build-essential libaio-dev thin-provisioning-tools
#RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y pkg-config libudev-dev
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y git emacs tmux tig strace gdb tree psmisc lsb-release

ADD lvm2/.gitconfig /root/.gitconfig
ADD lvm2/.tmux.conf /root/.tmux.conf

RUN (git clone git://sourceware.org/git/lvm2.git)

ENTRYPOINT ["/bin/bash"]
