#!/bin/sh

export CROSS_COMPILE=arm-linux-gnueabihf-

cd u-boot
git co -b v2017.11 v2017.11
make vexpress_ca9x4_defconfig
make all

#qemu-system-arm -machine vexpress-a9 -nographic -no-reboot -kernel u-boot
