FROM lttng
MAINTAINER Anders Wallin

# Building lttng repos
RUN (cd lttng-test; make rcs.patch)
RUN (cd lttng-test; make install.userspace-rcu)
RUN (cd lttng-test; make install.lttng-ust)
RUN (cd lttng-test; make install.lttng-tools)
RUN (cd lttng-test; make install babeltrace)

RUN mkdir -p /root/.ssh
ADD lttng/ssh.config /root/.ssh/config
