FROM lttng
MAINTAINER Anders Wallin

# Building lttng repos
RUN (cd lttng-test; make stable-2.8.checkout)
RUN (cd lttng-test; make install.userspace-rcu)
RUN (cd lttng-test; make install.lttng-ust)
RUN (cd lttng-test; make install.lttng-tools)
RUN (cd lttng-test; make install babeltrace)

RUN apt-get install -y vim sshpass

ADD lttng/test-live /root/test-live
RUN mkdir -p /root/.ssh
ADD lttng/ssh.config /root/.ssh/config
